sudo: false # use container-based infrastructure instead of legacy
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
env:
- DATABASE_URL=mysql://travis@127.0.0.1:3306/flask-boilerplate_test
install: pip install -r requirements/dev.txt
script:
- make test

after_success:
  - make report-coverage
  - pip install --quiet python-coveralls
  - coveralls
  - make check-style

notifications:
  slack:
    on_success: change
    secure: QAvf45sVae4uzqON/XmP2wy3GvmmB66ccjYsDzDq5Ig9TzXzvdcarRyMu0LsM2pxNwMc3luQVKcs04HX+52amyy8AG9ngwknNAGKeo5s0c6O8rWwAxo4+k9r54habHTPliMUkfvkuTVv40qTR1QgZEE/yGsxqQrfcbxB7Rr3LYo=
